# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DictionaryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDictionary = channel.unary_unary(
                '/dictonary.DictionaryService/GetDictionary',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.PickledData.FromString,
                _registered_method=True)


class DictionaryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDictionary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DictionaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDictionary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDictionary,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.PickledData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dictonary.DictionaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dictonary.DictionaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DictionaryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDictionary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dictonary.DictionaryService/GetDictionary',
            service__pb2.Empty.SerializeToString,
            service__pb2.PickledData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ObjectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObject = channel.unary_unary(
                '/dictonary.ObjectService/GetObject',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.PickledData.FromString,
                _registered_method=True)


class ObjectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.PickledData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dictonary.ObjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dictonary.ObjectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dictonary.ObjectService/GetObject',
            service__pb2.Empty.SerializeToString,
            service__pb2.PickledData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
